fruits = ["Mango", "Apple", "Banana", "Chickoo", "Custard Apple", "Strawberry"]
vegetables = ["Carrots", "Spinach", "Onion", "Kale", "Potato", "Capsicum", "Lettuce"]

print (type(fruits))
print(fruits)
#fruits.extend(vegetables)
#print(fruits)
#fruits.extend(vegetables[1])
print (fruits)
fruits.extend(vegetables[1:3])
print (fruits)
fruits.append("Garlic")
print (fruits)
fruits.insert(1,"Baby Spinach")
print (fruits)
fruits.remove("Baby Spinach")
print(fruits)
fruits.clear()
print(fruits)

vegetables.append("Onion")
print(vegetables)
vegetables.remove("Onion")
print(vegetables)
vegetables.remove("Onion")
print(vegetables)
vegetables.pop()
print(vegetables.index("Kale"))
print(vegetables.count("kale"))

lucky_nums=[8,5,9,0,3,2,6]
print(lucky_nums)
lucky_nums.sort()
print(lucky_nums)
lucky_nums.reverse()
print(lucky_nums)
lucky_nums2= lucky_nums.copy()
print(lucky_nums)
print(lucky_nums2)