phrase = "Giraffe Academy"
print (phrase + " is pretty cool!")
print (phrase.upper() + " looks amazing!")
print (phrase.isupper())
print (phrase.upper().isupper())
print (len(phrase))
print (phrase[3])
print (phrase.index("a"))
print (phrase.index("Acad"))
print (phrase.replace("Giraffe", "Elephant"))